#!/usr/bin/env php
<?php
declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use App\Core\Kernel;

$config = require_once __DIR__ . '/App/Config/app.php';

Kernel::start($config, true);