version: '3.7'

services:
  web:
    container_name: api_web
    build:
      context: ./Docker/web
    restart: 'always'
    ports:
      - 80:80
    volumes:
      - ./App:/App
      - ./Docker/Web/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - db

  php:
    container_name: api_php
    build:
      context: ./Docker/PHP
    restart: 'always'
    volumes:
      - ./App:/App

  db:
    container_name: api_db
    build:
      context: ./Docker/DB
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: secret

  phpmyadmin:
    container_name: api_phpmyadmin
    build:
      context: ./Docker/PHPMyAdmin
    restart: 'always'
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: api
      PMA_PASSWORD: secret
    links:
      - db