version: '3.7'

services:
  web:
    container_name: api_web
    build:
      context: ./Docker/web
    restart: 'always'
    ports:
      - 80:80
    volumes:
      - ./:/Site
      - ./Docker/Web/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - db

  php:
    container_name: api_php
    build:
      context: ./Docker/PHP
    restart: 'always'
    volumes:
      - ./:/Site

  db:
    container_name: api_db
    build:
      context: ./Docker/DB
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  phpmyadmin:
    container_name: api_phpmyadmin
    build:
      context: ./Docker/PHPMyAdmin
    restart: 'always'
    ports:
      - 8080:80
    environment:
      PMA_HOST: "${PMA_HOST}"
      PMA_PORT: "${PMA_PORT}"
      PMA_USER: "${PMA_USER}"
      PMA_PASSWORD: "${PMA_PASSWORD}"
    links:
      - db